### ISSUE TITLE
怎么在windows上编译

### ISSUE THREAD

**Issue by CAOLINAN** [Achain-Dev/Achain#81]
windows上编译的帮助文档贼鸡儿差，Achain_ROOT下并没有讲明LevelDB、fc等文档的来源以及作用，在windows下很难编译成功，在linux编译帮助里面也没看到fc的作用。另外linux的帮助为啥这么曲折，和windows风格都不一样。。

**Comment by Qipingsmile006** [comment]
Me too.

**Comment by owenSai** [comment]
github上下载Achain代码，依赖的lib需要单独download（Achain-Dev/lib），解压到\Achain\lib下就可以编译了，选择x64

**Comment by CAOLINAN** [comment]
@owenSai 解压完就根据命令行继续做？不用管fc目录吗？levelDB是下载的数据库？还是自己建的数据库目录？

**Comment by saiyang172** [comment]
对，解压到lib目录后，打开sln文件，选择x64,编译就可以了发自我的华为手机-------- 原始邮件 --------主题：Re: [Achain-Dev/Achain] 怎么在windows上编译 (#81)发件人：CAOLINAN 收件人：Achain-Dev/Achain 抄送：Subscribed @owenSai 解压完就根据命令行继续做？不用管fc目录吗？levelDB是下载的数据库？还是自己建的数据库目录？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Achain-Dev/Achain","title":"Achain-Dev/Achain","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Achain-Dev/Achain"}},"updates":{"snippets":[{"icon":"PERSON","message":"@CAOLINAN in #81: @owenSai 解压完就根据命令行继续做？不用管fc目录吗？levelDB是下载的数据库？还是自己建的数据库目录？"}],"action":{"name":"View Issue","url":"https://github.com/Achain-Dev/Achain/issues/81#issuecomment-360952418"}}}

**Comment by CAOLINAN** [comment]
报错，如下图所示，另外问下编译器版本用的啥。
![image](https://user-images.githubusercontent.com/16277926/35468022-c9f2e092-0351-11e8-8b40-a1375f919909.png)

**Comment by WillAchain** [comment]
windows 默认 vs2013
